<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

$GLOBALS['ebms_event_nodes'] = array(
    'ebms_event' => array(
        'name' => 'EBMS Event',
        'module' => 'ebms',
        'base' => 'node_content',
        'description' => 'A node describing an event suitable for the EBMS calendar.',
        'has_title' => true,
        'title_label' => 'Event Name'
    ),
);
?>
