ebms_core.settings:
  type: config_object
  label: EBMS custom configuration settings
  mapping:
    debug_level:
      type: integer
      label: Debug Logging Level
    dev_notif_addr:
      type: text
      label: Developer email notification address
    pubmed_missing_article_report_recips:
      type: text
      label: Recipients for Invalid PubMed IDs report
