<?php

// $Id$

/**
 *
 * @file
 *
 * Portal for PDQ Board members.
 *
 * "Editorial Board Management Site" (EBMS).
 *
 * Supported functionality includes:
 *   - literature review
 *   - calendar of events
 *   - meeting support information
 *   - announcements
 *   - threaded discussions
 *   - rosters and other reports
 *   - request forms (e.g., hotel reservations, reimbursements)
 */

/**
 *
 * Implements hook_menu.
 *
 * Creates our custom menus and other addressable pages.
 */
function ebms_menu() {
    return array(

        // LANDING PAGE
        'home' => array(
            'title' => 'Home',
            'page callback' => 'pdq_ebms_home',
            'file' => 'home.inc',
            'access callback' => true,
            #'menu_name' => 'main-menu',
            'weight' => 1,
        ),

        // CALENDAR
        'calendar' => array(
            'title' => 'Calendar',
            'page callback' => 'pdq_ebms_calendar',
            'file' => 'calendar.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 2,
        ),

        // POSTING DOCUMENTS
        'docs' => array(
            'title' => 'Docs',
            'page callback' => 'pdq_ebms_docs',
            'file' => 'docs.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 3,
        ),

        // TRAVEL
        'travel' => array(
            'title' => 'Travel',
            'page callback' => 'pdq_ebms_travel',
            'file' => 'travel.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 4,
        ),

        // REVIEW
        'review' => array(
            'title' => 'Review',
            'page callback' => 'pdq_ebms_review',
            'file' => 'review.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 5,
        ),

        // SUMMARIES
        'summaries' => array(
            'title' => 'Summaries',
            'page callback' => 'pdq_ebms_summaries',
            'file' => 'summaries.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 6,
        ),

        // FORUMS
        'forum' => array(
            'title' => 'Discussion',
            'page callback' => 'pdq_ebms_forum',
            'file' => 'forum.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 7,
        ),

        // ROSTER
        'roster' => array(
            'title' => 'Roster',
            'page callback' => 'pdq_ebms_roster',
            'file' => 'roster.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 8,
        ),

        // REPORTS
        'reports' => array(
            'title' => 'Reports',
            'page callback' => 'pdq_ebms_reports',
            'file' => 'reports.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 9,
        ),

        // Testing article search
        'articlesearch' => array(
            'title' => 'Search for Articles',
            'page callback' => 'pdq_ebms_artsearch',
            'file' => 'art_search.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 6,
        ),
        // Testing for Alan
        'alantest' => array(
            'title' => 'AlanTest',
            'page callback' => 'pdq_ebms_alantest',
            'file' => 'alan.inc',
            'access callback' => true,
            'menu_name' => 'main-menu',
            'weight' => 20,
        ),

    );
}
